version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        ports:
            - 27017:27017
        command: mongod --smallfiles
    api:
        build: .
        container_name: "pack"
        ports:
            - "8287:8287"
        volumes:
            - /home/luisfer/appdata/pack/conf:/etc/pack/conf